close all
clear variables

base_dir = { ...
    'F:\full\Processed_PIV_validation\90degree_400light_100hz_3000dt', ...
    'F:\full\Processed_PIV_validation\90degree_250light_250hz_1000dt', ...
    'F:\full\Processed_PIV_validation\60degree_400light_100hz_3000dt_reverse', ...
    'F:\full\Processed_PIV_validation\60degree_250light_250hz_1000dt_reverse', ...
    'F:\full\Processed_PIV_validation\60degree_400light_100hz_3000dt', ...
    'F:\full\Processed_PIV_validation\60degree_250light_250hz_1000dt', ...
    'F:\full\Processed_PIV_validation\30degree_400light_100hz_3000dt_reverse', ...
    'F:\full\Processed_PIV_validation\30degree_250light_250hz_1000dt_reverse', ...
    'F:\full\Processed_PIV_validation\30degree_400light_100hz_3000dt', ...
    'F:\full\Processed_PIV_validation\30degree_250light_250hz_1000dt', ...
};

scalefactor = 9.53;
N = 18000;

fig_files = { ...
    'autocorr_mode_1.fig', ...
    'autocorr_mode_2.fig', ...
    'autocorr_mode_3.fig', ...
    'CumulativeEnergyDistribution_pass5.fig', ...
    'Pass 5 U Mode 3 16x16.fig', ...
    'Pass 5 U Mode 2 16x16.fig', ...
    'Pass 5 U Mode 1 16x16.fig' ...
};

for base_idx = 1:length(base_dir)
    disp(['Processing base directory ', num2str(base_idx), ' of ', num2str(length(base_dir))]);
    
    % Construct the path to the Statistics folder
    statistics_dir = fullfile(base_dir{base_idx}, 'Statistics', num2str(N), 'Cam1', 'Instantaneous', 'Calibrated', 'Below');
    
    % Open each required .fig file
    for fig_idx = 1:length(fig_files)
        fig_path = fullfile(statistics_dir, fig_files{fig_idx});
        if exist(fig_path, 'file')
            fig_handle = openfig(fig_path, 'new'); % Open figure
            
            % Find and modify the title size
            ax = findall(fig_handle, 'Type', 'axes'); % Find all axes in the figure
            for a = 1:length(ax)
                t = get(ax(a), 'Title'); % Get title object
                set(t, 'FontSize', 30); % Set title font size to 30
            end
            
            disp(['Opened and updated title size: ', fig_files{fig_idx}]);
        else
            warning(['File not found: ', fig_path]);
        end
    end
    close all
end
